package com.mycompany.quanlyquancoffee.Views;
import DTO.BanDTO;
import DTO.ChiTietMonDTO;
import DTO.HoaDonChiTietDTO;
import DTO.HoaDonResponse;
import DTO.KhuVucDTO;
import javax.swing.JOptionPane;
import DTO.SanPhamDTO;
import DTO.TaoHoaDonRequest;
import DTO.ThemMonRequest;
import com.mycompany.quanlyquancoffee.Controllers.BanController;
import com.mycompany.quanlyquancoffee.Controllers.KhuVucController;
import com.mycompany.quanlyquancoffee.Helper.ApiBan;
import com.mycompany.quanlyquancoffee.Helper.PdfExporter;
import com.mycompany.quanlyquancoffee.Helper.ApiHoaDon;
import com.mycompany.quanlyquancoffee.Helper.ApiSanpham;
import com.mycompany.quanlyquancoffee.Helper.UserSession;

import com.mycompany.quanlyquancoffee.Views.XemHoaDonForm;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.FlowLayout;
import static java.awt.Frame.DEFAULT_CURSOR;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Label;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.math.BigDecimal;
import java.net.HttpURLConnection;
import java.net.URL;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JToolBar;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author omar
 */
public class FormBan extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public FormBan() {
        initComponents();
        
       
    }
private Map<String, String> mapMaBanTenBan = new HashMap<>();

private boolean vuaDatBan = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        btndatban = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Menuorder = new javax.swing.JPanel();
        tabs2 = new javax.swing.JTabbedPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblHinh = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnorder = new javax.swing.JButton();
        lblten = new javax.swing.JTextField();
        lblgia = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtmahoadon = new javax.swing.JTextField();
        txtban = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtmaban = new javax.swing.JTextField();
        txtNgay = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblchitietban = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbltongtien = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtgio = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnxembill = new javax.swing.JButton();
        btnthanhtoan = new javax.swing.JButton();
        btnchuyenban = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(44, 62, 80));
        jPanel13.setForeground(new java.awt.Color(44, 62, 80));
        jPanel13.setPreferredSize(new java.awt.Dimension(1370, 780));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(248, 148, 6));
        jPanel3.setPreferredSize(new java.awt.Dimension(1368, 780));

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabel1.setBackground(java.awt.Color.black);
        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 2, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.green);
        jLabel1.setText("<---Tro lai ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Adobe Caslon Pro", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quan Ly Ban Hang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(455, 455, 455)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelClose))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(482, 671));
        jPanel2.setMinimumSize(new java.awt.Dimension(482, 671));

        tab.setBackground(new java.awt.Color(44, 62, 80));
        tab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab.setMaximumSize(new java.awt.Dimension(32767, 548));
        tab.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabComponentShown(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Thông tin bàn");

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));

        jButton3.setBackground(new java.awt.Color(34, 167, 240));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        btndatban.setBackground(new java.awt.Color(34, 167, 240));
        btndatban.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndatban.setForeground(new java.awt.Color(255, 255, 255));
        btndatban.setText("Đặt bàn");
        btndatban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatbanActionPerformed(evt);
            }
        });
        jPanel4.add(btndatban);

        jButton4.setBackground(new java.awt.Color(34, 167, 240));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Làm mới");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);

        jButton7.setBackground(new java.awt.Color(34, 167, 240));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Page Facebook Hỗ Trợ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        Menuorder.setBackground(new java.awt.Color(44, 62, 80));
        Menuorder.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabs2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabs2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Danh sách sản phẩm");

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrderMouseClicked(evt);
            }
        });
        tblOrder.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblOrderComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrder);

        jPanel6.setBackground(new java.awt.Color(44, 62, 80));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Mô tả sản phẩm");

        lblHinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHinh.setForeground(new java.awt.Color(236, 240, 241));

        jPanel9.setBackground(new java.awt.Color(44, 62, 80));

        btnorder.setBackground(new java.awt.Color(34, 167, 240));
        btnorder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnorder.setForeground(new java.awt.Color(255, 255, 255));
        btnorder.setText("ORDER");
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });

        lblgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblgiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblten, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnorder)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addComponent(lblgia))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnorder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        jButton6.setBackground(new java.awt.Color(204, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Tìm nhanh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtsearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(2, 2, 2))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        javax.swing.GroupLayout MenuorderLayout = new javax.swing.GroupLayout(Menuorder);
        Menuorder.setLayout(MenuorderLayout);
        MenuorderLayout.setHorizontalGroup(
            MenuorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuorderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        MenuorderLayout.setVerticalGroup(
            MenuorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(44, 62, 80));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setPreferredSize(new java.awt.Dimension(500, 524));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Mã hóa đơn:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Đang Chọn :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("Ngày");

        txtmahoadon.setBackground(new java.awt.Color(108, 122, 137));
        txtmahoadon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtmahoadon.setForeground(new java.awt.Color(228, 241, 254));
        txtmahoadon.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtmahoadonInputMethodTextChanged(evt);
            }
        });

        txtban.setBackground(new java.awt.Color(108, 122, 137));
        txtban.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtban.setForeground(new java.awt.Color(228, 241, 254));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("Mã Bàn :");

        txtmaban.setBackground(new java.awt.Color(108, 122, 137));
        txtmaban.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtmaban.setForeground(new java.awt.Color(228, 241, 254));

        txtNgay.setBackground(new java.awt.Color(108, 122, 137));
        txtNgay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNgay.setForeground(new java.awt.Color(228, 241, 254));

        jScrollPane8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane8MouseClicked(evt);
            }
        });

        tblchitietban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ HDCT", "MÃ MÓN", "TÊN MÓN", "GIÁ TIỀN", "SỐ LƯỢNG", "THÀNH TIỀN"
            }
        ));
        tblchitietban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblchitietbanMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblchitietban);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setText("DANH SÁCH ORDER SẢN PHẨM");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setText("Tổng tiền:");

        jPanel8.setBackground(new java.awt.Color(44, 62, 80));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbltongtien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltongtien.setForeground(java.awt.Color.red);
        lbltongtien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltongtien.setText("0");
        lbltongtien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltongtien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltongtien, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(236, 240, 241));
        jLabel13.setText("Vnđ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(236, 240, 241));
        jLabel16.setText("Giờ");

        txtgio.setBackground(new java.awt.Color(108, 122, 137));
        txtgio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtgio.setForeground(new java.awt.Color(228, 241, 254));

        jPanel5.setBackground(new java.awt.Color(44, 62, 80));

        btnxembill.setBackground(new java.awt.Color(34, 167, 240));
        btnxembill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnxembill.setForeground(new java.awt.Color(255, 255, 255));
        btnxembill.setText("Xem bill");
        btnxembill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxembillActionPerformed(evt);
            }
        });

        btnthanhtoan.setBackground(new java.awt.Color(34, 167, 240));
        btnthanhtoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnthanhtoan.setForeground(new java.awt.Color(255, 255, 255));
        btnthanhtoan.setText("Thanh toán");
        btnthanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthanhtoanActionPerformed(evt);
            }
        });

        btnchuyenban.setBackground(new java.awt.Color(34, 167, 240));
        btnchuyenban.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnchuyenban.setForeground(new java.awt.Color(255, 255, 255));
        btnchuyenban.setText("Chuyển bàn - Ghép bàn");
        btnchuyenban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchuyenbanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(btnchuyenban)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnxembill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnthanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnchuyenban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnxembill, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnthanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgay)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(95, 95, 95)
                                .addComponent(txtgio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 16, Short.MAX_VALUE))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtban, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(218, 218, 218)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtmaban, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(176, 176, 176)
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13))))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtmahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtmaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtgio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menuorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menuorder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1384, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 1384, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("600");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
   private void loadsanpham() {
    try {
        String[] head = {"Mã món", "Tên món", "Giá", "Hình ảnh"};
        DefaultTableModel tb = new DefaultTableModel(head, 0);

        List<SanPhamDTO> ds = ApiSanpham.layDanhSachSanPham();

        for (SanPhamDTO sp : ds) {
            tb.addRow(new Object[]{
                sp.getMaMon(),
                sp.getTenMon(),
                sp.getGia(),
                sp.getHinhAnh() // ✅ THÊM CỘT NÀY
            });
        }

        tblOrder.setModel(tb);

        // ✅ ẨN CỘT HÌNH ẢNH (nếu muốn) để vẫn lấy được
        tblOrder.getColumnModel().getColumn(3).setMinWidth(0);
        tblOrder.getColumnModel().getColumn(3).setMaxWidth(0);
        tblOrder.getColumnModel().getColumn(3).setWidth(0);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu sản phẩm", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}
   
   private void loadban() {
    try {
        tab.removeAll();  // Xoá tất cả các tab khu vực cũ
        mapMaBanTenBan.clear();
        List<KhuVucDTO> dsKhuVuc = ApiBan.layDanhSachKhuVuc();
        for (KhuVucDTO kv : dsKhuVuc) {
        /*      if (!"Trống".equalsIgnoreCase(ban.getTrangThai())) {
        continue; // ❌ bỏ qua bàn không trống
    }*/

            JPanel panelKhuVuc = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 5));

            List<BanDTO> dsBan = ApiBan.layDanhSachBanTheoKhuVuc(kv.getMaKV());
            
            for (BanDTO ban : dsBan) {
                final BanDTO banCopy = ban;
                mapMaBanTenBan.put(ban.getMaBan(), ban.getTenBan());
                JButton btnBan = new JButton(banCopy.getTenBan());
               
                btnBan.setPreferredSize(new Dimension(100, 100));
                btnBan.setForeground(Color.WHITE);

                // Set icon nếu cần
                java.net.URL imgURL = getClass().getResource("/Pictures/Hinh/admin.jpg");
                if (imgURL != null) {
                    ImageIcon icon = new ImageIcon(imgURL);
                    Image scaledImage = icon.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
                    btnBan.setIcon(new ImageIcon(scaledImage));
                }

                // 🟢 Ưu tiên đọc trạng thái bàn từ DB
                if ("Trống".equalsIgnoreCase(banCopy.getTrangThai())) {
                    btnBan.setBackground(Color.GREEN);
                    btnBan.setToolTipText("Bàn trống");
                } else {
                    try {
                        HoaDonChiTietDTO hoaDon = ApiHoaDon.layHoaDonHomNayTheoBan(banCopy.getMaBan());

                        boolean coMon = !hoaDon.getMonAn().isEmpty();
                        boolean daThanhToan = "Da thanh toan".equalsIgnoreCase(hoaDon.getTrangThai());

                        if (daThanhToan) {
                            btnBan.setBackground(Color.GRAY);
                            btnBan.setToolTipText("Đã đặt - Đã thanh toán");
                        } else if (coMon) {
                            btnBan.setBackground(Color.BLUE);
                            btnBan.setToolTipText("Đã đặt - Đã order, chưa thanh toán");
                        } else {
                            btnBan.setBackground(Color.ORANGE);
                            btnBan.setToolTipText("Đã đặt - Chưa order");
                        }
                    } catch (Exception ex) {
                        btnBan.setBackground(Color.ORANGE);
                        btnBan.setToolTipText("Đã đặt - Không có hóa đơn hôm nay");
                    }
                }

                // 🖱️ Sự kiện click vào nút bàn
                btnBan.addActionListener(e -> {
                try {
                    // Gán mã và tên bàn vào TextField
                    txtmaban.setText(banCopy.getMaBan());
                    String maBan = banCopy.getMaBan();
                    String tenBan = mapMaBanTenBan.getOrDefault(maBan, "Không rõ");
                    txtban.setText(tenBan); 
                   // 💡 Gán tên bàn tại đây

                    if (vuaDatBan) {
                        vuaDatBan = false;
                        return;
                    }

                    if ("Trống".equalsIgnoreCase(banCopy.getTrangThai())) {
                        JOptionPane.showMessageDialog(this, "Bàn đang trống, không có hóa đơn hôm nay.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        clearHoaDonUI();
                        return;
                    }

                    HoaDonChiTietDTO hd = ApiHoaDon.layHoaDonHomNayTheoBan(banCopy.getMaBan());

                    txtmahoadon.setText(hd.getMaHd());
                    txtNgay.setText(hd.getNgayLap());
                    txtgio.setText(hd.getGio());

                    // Load danh sách món ăn
                    String[] columnNames = {"Mã HDCT", "Mã Món", "Tên Món", "Giá Tiền", "Số Lượng", "Thành Tiền"};
                    DefaultTableModel model = new DefaultTableModel(columnNames, 0);

                    for (ChiTietMonDTO mon : hd.getMonAn()) {
                        BigDecimal thanhTien = mon.getGiaLucBan().multiply(BigDecimal.valueOf(mon.getSoLuong()));
                        model.addRow(new Object[]{
                            hd.getMaHd(), mon.getMaMon(), mon.getTenMon(),
                            mon.getGiaLucBan(), mon.getSoLuong(), thanhTien
                        });
                    }

                    tblchitietban.setModel(model);
                    DecimalFormat df = new DecimalFormat("#,###");
                    lbltongtien.setText(df.format(hd.getTongTien()) + " đ");

                    btnorder.setEnabled(true);
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Không có hóa đơn hôm nay cho bàn này", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    clearHoaDonUI();
                    btnorder.setEnabled(true);
                }
            });


                            panelKhuVuc.add(btnBan);
                        }

                        tab.addTab(kv.getTenKV(), new JScrollPane(panelKhuVuc));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
}

   /*private void timVaHienThiBan(String maBan) {
    if (maBan == null || maBan.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã bàn cần tìm.");
        return;
    }

    // Gọi API để tìm bàn
    List<BanDTO> dsBan = ApiBan.timBan(maBan.trim());

    if (dsBan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy bàn với mã: " + maBan);
        return;
    }

    BanDTO ban = dsBan.get(0);

    // Gán thông tin bàn vào giao diện
    txtmaban.setText(ban.getMaBan());
    txtban.setText(ban.getTenBan());

    // Tô sáng nút bàn và chuyển đến tab khu vực
    highlightButtonForBan(ban.getTenBan());

    // Nếu bàn đã được đặt, hiển thị hóa đơn
    if (!"Trống".equalsIgnoreCase(ban.getTrangThai())) {
        try {
            HoaDonChiTietDTO hd = ApiHoaDon.layHoaDonHomNayTheoBan(ban.getMaBan());

            txtmahoadon.setText(hd.getMaHd());
            txtNgay.setText(hd.getNgayLap());
            txtgio.setText(hd.getGio());

            DefaultTableModel model = new DefaultTableModel(new String[]{
                "Mã HDCT", "Mã Món", "Tên Món", "Giá", "Số lượng", "Thành tiền"
            }, 0);

            for (ChiTietMonDTO mon : hd.getMonAn()) {
                BigDecimal thanhTien = mon.getGiaLucBan().multiply(BigDecimal.valueOf(mon.getSoLuong()));
                model.addRow(new Object[]{
                    hd.getMaHd(), mon.getMaMon(), mon.getTenMon(),
                    mon.getGiaLucBan(), mon.getSoLuong(), thanhTien
                });
            }

            tblchitietban.setModel(model);

            DecimalFormat df = new DecimalFormat("#,###");
            lbltongtien.setText(df.format(hd.getTongTien()) + " đ");
            btnorder.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Không có hóa đơn hôm nay cho bàn này.");
            clearHoaDonUI();
            btnorder.setEnabled(true);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Bàn đang trống, chưa có hóa đơn.");
        clearHoaDonUI();
        btnorder.setEnabled(false);
    }
   
}


   private void highlightButtonForBan(String tenBan) {
    for (int i = 0; i < tab.getTabCount(); i++) {
        Component comp = ((JScrollPane) tab.getComponentAt(i)).getViewport().getView();

        if (comp instanceof JPanel panelKhuVuc) {
            for (Component c : panelKhuVuc.getComponents()) {
                if (c instanceof JButton btn && btn.getText().equalsIgnoreCase(tenBan)) {
                    tab.setSelectedIndex(i);
                    btn.setBorder(BorderFactory.createLineBorder(Color.RED, 2)); // ✅ chỉ tô viền
                    btn.requestFocus();
                    btn.scrollRectToVisible(btn.getBounds());2
                    return;
                }
            }
        }
    }
}
   */

// ✅ Hàm tiện ích để reset UI khi không có hóa đơn
private void clearHoaDonUI() {
    txtmahoadon.setText("");
    txtNgay.setText("");
    txtgio.setText("");
    lbltongtien.setText("");
    tblchitietban.setModel(new DefaultTableModel());
    btnorder.setEnabled(false);
}





    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
//jpancapnhat.setVisible(false);
//      lolhome();        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel13MouseClicked
    
    private void updateChiTietHoaDonTable(HoaDonChiTietDTO dto) {
    String[] columnNames = {"Mã HDCT", "Mã Món", "Tên Món", "Giá", "Số Lượng", "Thành Tiền"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);

    for (ChiTietMonDTO mon : dto.getMonAn()) {
        BigDecimal thanhTien = mon.getGiaLucBan().multiply(BigDecimal.valueOf(mon.getSoLuong()));
        model.addRow(new Object[]{
            dto.getMaHd(),
            mon.getMaMon(),
            mon.getTenMon(),
            mon.getGiaLucBan(),
            mon.getSoLuong(),
            thanhTien
        });
    }
    lbltongtien.setText(dto.getTongTien().toString() + " đ");
    tblchitietban.setModel(model);
}

    
    
    private void tblchitietbanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblchitietbanMouseClicked
        int selectedRow = tblchitietban.getSelectedRow();
    if (selectedRow == -1) return;

    Object valMaHd = tblchitietban.getValueAt(selectedRow, 0);
    Object valMaMon = tblchitietban.getValueAt(selectedRow, 1);
    Object valTenMon = tblchitietban.getValueAt(selectedRow, 2);
    Object valGia = tblchitietban.getValueAt(selectedRow, 3);
    Object valSoLuong = tblchitietban.getValueAt(selectedRow, 4);

    if (valMaHd == null || valMaMon == null || valTenMon == null || valGia == null || valSoLuong == null) {
        JOptionPane.showMessageDialog(this, "Một số thông tin món đang bị thiếu hoặc chưa load xong.", "Lỗi dữ liệu", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String maHd = valMaHd.toString();
    String maMon = valMaMon.toString();
    String tenMon = valTenMon.toString();
    BigDecimal gia = new BigDecimal(valGia.toString());
    int soLuong = Integer.parseInt(valSoLuong.toString());

    // Gọi form Order
    Odermon form = new Odermon(this); // sửa nếu bạn dùng Dialog khác JFrame
    form.setThongTinMon(maHd, maMon, tenMon, gia, soLuong);
    form.setVisible(true);
     this.dispose();
        
    }//GEN-LAST:event_tblchitietbanMouseClicked

    private void txtmahoadonInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtmahoadonInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmahoadonInputMethodTextChanged

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
            String maBan = txtmaban.getText();
         String maNv = UserSession.getMaNV();

         if (maBan.isEmpty()) {
             JOptionPane.showMessageDialog(this, "Vui lòng chọn bàn trước khi order!", "Thông báo", JOptionPane.WARNING_MESSAGE);
             return;
         }

         int row = tblOrder.getSelectedRow();
         if (row == -1) {
             JOptionPane.showMessageDialog(this, "Vui lòng chọn món!", "Thông báo", JOptionPane.WARNING_MESSAGE);
             return;
         }

         try {
    String maHd;
        try {
            // ✅ 1. Kiểm tra hóa đơn hôm nay theo bàn
            HoaDonChiTietDTO dto = ApiHoaDon.layHoaDonHomNayTheoBan(maBan); // ← API này KHÔNG quan tâm trạng thái
            if (!dto.getTrangThai().equalsIgnoreCase("Chua thanh toan")) {
                // Nếu hóa đơn hôm nay đã thanh toán → tạo hóa đơn mới
                throw new Exception("Đã thanh toán rồi");
            }
            maHd = dto.getMaHd(); // Có hóa đơn chưa thanh toán
        } catch (Exception ex) {
            // ❌ Không có hóa đơn hôm nay hoặc đã thanh toán → tạo mới
            TaoHoaDonRequest req = new TaoHoaDonRequest();
            req.setMaBan(maBan);
            req.setMaNv(maNv);
            HoaDonResponse res = ApiHoaDon.taoHoaDon(req);
            maHd = res.getMaHoaDon();
        }

             // ✅ 2. Thêm món
             String maMon = tblOrder.getValueAt(row, 0).toString();
             BigDecimal gia = new BigDecimal(tblOrder.getValueAt(row, 2).toString());

             ChiTietMonDTO mon = new ChiTietMonDTO();
             mon.setMaMon(maMon);
             mon.setGiaLucBan(gia);
             mon.setSoLuong(1); // mặc định 1

             ThemMonRequest themReq = new ThemMonRequest();
             themReq.setMaHd(maHd);
             themReq.setMonAn(List.of(mon));

             ApiHoaDon.themMonVaoHoaDon(themReq);

             txtmahoadon.setText(maHd); // hiển thị mã hóa đơn

             JOptionPane.showMessageDialog(this, "Thêm món thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);

             // ✅ 3. Load lại chi tiết hóa đơn
             HoaDonChiTietDTO dtoMoi = ApiHoaDon.layChiTietHoaDonTheoBan(maBan);
             updateChiTietHoaDonTable(dtoMoi);
             loadban();
         } catch (Exception e) {
             e.printStackTrace();
             JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
         }

      
    }//GEN-LAST:event_btnorderActionPerformed

    private void tblOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrderMouseClicked
               // TODO add your handling code here:
        int selectedRow = tblOrder.getSelectedRow();
       if (selectedRow != -1) {
           String tenFileAnh = tblOrder.getValueAt(selectedRow, 3).toString();
           String ten = (String) tblOrder.getValueAt(selectedRow,1);
           String gia = tblOrder.getValueAt(selectedRow, 2).toString();
           // Đường dẫn trong resource (đặt trong src/main/resources/Pictures/sanpham/)
           java.net.URL imgURL = getClass().getResource("/Pictures/sanpham/" + tenFileAnh);
           if (imgURL != null) {
               ImageIcon icon = new ImageIcon(imgURL);
               Image scaledImage = icon.getImage().getScaledInstance(
                       lblHinh.getWidth(), 
                       lblHinh.getHeight(), 
                       Image.SCALE_SMOOTH
               );
               lblHinh.setIcon(new ImageIcon(scaledImage));
               lblten.setText(ten);
               lblgia.setText(gia);
           } else {
               System.err.println("Ảnh không tìm thấy trong resources/Pictures/sanpham/" + tenFileAnh);
               lblHinh.setIcon(null);
           }
       }       
    }//GEN-LAST:event_tblOrderMouseClicked

    private void tabs2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabs2MouseClicked
                // TODO add your handling code here:
    }//GEN-LAST:event_tabs2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     // TODO add your handling code here:
               String maBan = txtmaban.getText().trim();
                if (maBan.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy mã bàn để trả.");
                    return;
                }

                try {
                    // Gửi yêu cầu PUT đến API trả bàn
                    URL url = new URL("http://localhost:1234/api/ban/tra-ban/" + maBan);
                    HttpURLConnection conn = (HttpURLConnection) url.openConnection();
                    conn.setRequestMethod("PUT");
                    conn.setDoOutput(true);

                    int responseCode = conn.getResponseCode();
                    if (responseCode == 200) {
                        JOptionPane.showMessageDialog(this, "Bàn đã được trả thành công!");
                        loadban();
                        // Có thể làm mới bảng hiển thị danh sách bàn ở đây nếu cần
                    } else {
                        JOptionPane.showMessageDialog(this, "Trả bàn thất bại. Mã lỗi: " + responseCode);
                    }
                    loadban();
                    conn.disconnect();
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Lỗi khi trả bàn: " + e.getMessage());
                }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btndatbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatbanActionPerformed
        Menuorder.setVisible(false);                                
        String maBan = txtmaban.getText();
        if (maBan == null || maBan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bàn trước khi đặt.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Gọi API cập nhật trạng thái bàn sang "Đang sử dụng"
            boolean thanhCong = ApiBan.capNhatTrangThaiBan(maBan, "Dang su dung");
            if (thanhCong) {
                JOptionPane.showMessageDialog(this, "Đặt bàn thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                vuaDatBan = true;
                Menuorder.setVisible(true);
                btnorder.setEnabled(true);

                // 🔄 Load lại bàn để cập nhật trạng thái/màu sắc
                loadban();
            } else {
                JOptionPane.showMessageDialog(this, "Không thể đặt bàn. Vui lòng thử lại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối khi đặt bàn.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btndatbanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         trogiupban help = new trogiupban();
            help.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked


    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked

        System.exit(0);

    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void btnxembillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxembillActionPerformed
        try {
        String maBan = txtmaban.getText(); // lấy mã bàn từ ô nhập hoặc giao diện

        HoaDonChiTietDTO dto = ApiHoaDon.layHoaDonHomNayTheoBan(maBan);

        // ✅ Kiểm tra nếu đã thanh toán thì không mở form
        if ("Da thanh toan".equalsIgnoreCase(dto.getTrangThai())) {
            JOptionPane.showMessageDialog(this, "Bàn đang trống (đã thanh toán hóa đơn).", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // ✅ Nếu chưa thanh toán thì mở form xem hóa đơn
        XemHoaDonForm xem = new XemHoaDonForm(this, dto);
        xem.setVisible(true);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }




    }//GEN-LAST:event_btnxembillActionPerformed

    private void btnthanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthanhtoanActionPerformed

    String maBan = txtmaban.getText(); // Lấy bàn đang chọn

    try {
        // 1. Lấy hóa đơn hôm nay (bất kể trạng thái)
        HoaDonChiTietDTO hd = ApiHoaDon.layHoaDonHomNayTheoBan(maBan);

        if ("Da thanh toan".equalsIgnoreCase(hd.getTrangThai())) {
            JOptionPane.showMessageDialog(this, "Hóa đơn đã thanh toán rồi!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Gọi API để chuyển trạng thái
        ApiHoaDon.thanhToan(hd.getMaHd());
        JOptionPane.showMessageDialog(this, "Đã thanh toán thành công!");

        // 3. Hỏi người dùng có muốn in hóa đơn không?
       

            // Mở file chooser
            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Chọn nơi lưu hóa đơn PDF");
            chooser.setSelectedFile(new File("HoaDon_" + hd.getMaHd() + ".pdf"));

            int userSelection = chooser.showSaveDialog(this);
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fileToSave = chooser.getSelectedFile();

                // Gọi hàm xuất PDF
                HoaDonChiTietDTO hdDaCapNhat = ApiHoaDon.layHoaDonHomNayTheoBan(maBan); // lấy lại bản mới sau thanh toán
                PdfExporter.xuatHoaDonPdf(hdDaCapNhat, fileToSave.getAbsolutePath());

                JOptionPane.showMessageDialog(this, "Đã in hóa đơn vào:\n" + fileToSave.getAbsolutePath());
            }
        

        // Cập nhật lại giao diện bàn (nếu có)
        loadban();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi thanh toán: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

// TODO add your handling code here:
    }//GEN-LAST:event_btnthanhtoanActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
             // TODO add your handling code here:
             // TODO add your handling code here:
        MainJFrame sp = new MainJFrame();
        sp.setVisible(true);
        sp.pack();
        sp.setLocationRelativeTo(null);
        sp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnchuyenbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchuyenbanActionPerformed
           String tenBan = txtban.getText();         // Tên bàn đang chọn
            String maBan = txtmaban.getText();        // Mã bàn
            String maHoaDon = txtmahoadon.getText();  // Mã hóa đơn

            if (maBan.isEmpty() || maHoaDon.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn bàn đã có hóa đơn để chuyển!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Chuyenban formChuyen = new Chuyenban(tenBan, maBan, maHoaDon);
            formChuyen.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnchuyenbanActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void lblgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblgiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblgiaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        String keyword = txtsearch.getText().trim();
        try {
              String[] head = {"Mã món", "Tên món", "Giá", "Hình ảnh"};
            DefaultTableModel tb = new DefaultTableModel(head, 0);
            List<SanPhamDTO> ds = ApiSanpham.timSanPhamGanDung(keyword);

            for (SanPhamDTO sp : ds) {
                tb.addRow(new Object[]{
                    sp.getMaMon(),
                    sp.getTenMon(),
                    sp.getGia(),
                    sp.getHinhAnh() 
                });
            }
              // ✅ ẨN CỘT HÌNH ẢNH (nếu muốn) để vẫn lấy được
            tblOrder.getColumnModel().getColumn(3).setMinWidth(0);
            tblOrder.getColumnModel().getColumn(3).setMaxWidth(0);
            tblOrder.getColumnModel().getColumn(3).setWidth(0);
            tblOrder.setModel(tb);
         } catch (Exception e) {
             e.printStackTrace();
         }
        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    
  
    
    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
        
    }//GEN-LAST:event_txtsearchKeyPressed

    private void tabComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tabComponentShown

    private void tblOrderComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblOrderComponentShown
        // TODO add your handling code here:
       loadsanpham();
    }//GEN-LAST:event_tblOrderComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
                                         
        // TODO add your handling code here:
       loadsanpham();
       loadban();
       // 🔒 Vô hiệu hóa nút Order
            
                                   
   
    }//GEN-LAST:event_formWindowOpened

    private void jScrollPane8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane8MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jScrollPane8MouseClicked
   




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menuorder;
    private javax.swing.JButton btnchuyenban;
    private javax.swing.JButton btndatban;
    private javax.swing.JButton btnorder;
    private javax.swing.JButton btnthanhtoan;
    private javax.swing.JButton btnxembill;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JTextField lblgia;
    private javax.swing.JTextField lblten;
    private javax.swing.JLabel lbltongtien;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTabbedPane tabs2;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblchitietban;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtban;
    private javax.swing.JTextField txtgio;
    private javax.swing.JTextField txtmaban;
    private javax.swing.JTextField txtmahoadon;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
