package com.mycompany.quanlyquancoffee.Views;

import DTO.SanPhamDTO;
import com.mycompany.quanlyquancoffee.Helper.ApiSanpham;
import com.mycompany.quanlyquancoffee.Helper.ApiLoaiMon;
import com.mycompany.quanlyquancoffee.Helper.ImageRenderer;
import com.mycompany.quanlyquancoffee.Helper.UserSession;
import com.mycompany.quanlyquancoffee.Models.LoaiMon;
import com.mycompany.quanlyquancoffee.Models.SanPham;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author omar
 */
public class SanPhamJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public SanPhamJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);// center form in the screen
        LoadSanPham();
        LoadDanhMuc();
        LoadDanhSachMon();
        
        /*
        if(!UserSession.getQuyen().equals("admin")){
            btn_Sua.setEnabled(false);
            btn_Xoa.setEnabled(false);
            btn_ThemLM.setEnabled(false);
            btn_SuaLM.setEnabled(false);
            btn_XoaLM.setEnabled(false);
        }
        */
    }

    private void LoadDanhSachMon(){
        try {           
        listmon.removeAll();
        DefaultListModel<String> model = new DefaultListModel<>();
        
        List<LoaiMon> ds = ApiLoaiMon.layDanhSachLoaiMon();
        
        for(LoaiMon lm : ds){
                model.addElement(lm.toString());
            }
        
        listmon.setModel(model);
        listmon.setSelectedIndex(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    Map<String, String> danhMucMap = new HashMap<>();
    private void LoadDanhMuc(){
        try {
            Connection con = Connect.ConnectDB.KetnoiDB();
            String sql = "Select * From loai_mon";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            cbo_DanhMuc.addItem("---Chọn loại món---");
            danhMucMap.put("---Chọn loại món---","");
            while(rs.next()){
                cbo_DanhMuc.addItem(rs.getString("ten_loai"));
                danhMucMap.put(rs.getString("ten_loai"), rs.getString("ma_loai"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void LoadSanPham(){
        try {
            tbl_Mon.removeAll();
            String[] head = {"Mã món", "Tên món", "Giá", "Loại món", "Hình ảnh"};
            DefaultTableModel tb = new DefaultTableModel(head, 0);
            
            List<SanPhamDTO> ds = ApiSanpham.layDanhSachSanPham();
            
            for(SanPhamDTO sp : ds){
                tb.addRow(new Object[]{
                    sp.getMaMon(),
                    sp.getTenMon(),
                    sp.getGia(),
                    sp.getTenLoai(),
                    sp.getHinhAnh()
                });
            }
            
            tbl_Mon.getColumnModel().getColumn(4).setCellRenderer(new ImageRenderer());
            tbl_Mon.setRowHeight(60);
            tbl_Mon.setModel(tb);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    void clear() {
        txt_MaMon.setText("");
        cbo_DanhMuc.setSelectedIndex(0);
        txt_TenMon.setText("");
        txt_DonGia.setText("");
        lblHinh.setIcon(null);
        txt_MaMon.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_Close = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_Minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PanelThucdon = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listmon = new javax.swing.JList<>();
        txtMaLM = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTenLoaiMon = new javax.swing.JTextField();
        btn_ThemLM = new javax.swing.JButton();
        btn_SuaLM = new javax.swing.JButton();
        btn_XoaLM = new javax.swing.JButton();
        lblguita = new javax.swing.JLabel();
        btn_TaoMoiML = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_Mon = new javax.swing.JTable();
        txt_TenMon = new javax.swing.JTextField();
        txt_MaMon = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_DonGia = new javax.swing.JTextField();
        cbo_DanhMuc = new javax.swing.JComboBox<>();
        btn_Them = new javax.swing.JButton();
        btn_TaoMoi = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        btn_ChonHinh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblbanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 52));

        label_Close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_Close.setForeground(new java.awt.Color(255, 255, 255));
        label_Close.setText("X");
        label_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_CloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Adobe Caslon Pro", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("San Pham");

        label_Minimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_Minimize.setForeground(new java.awt.Color(255, 255, 255));
        label_Minimize.setText("-");
        label_Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_MinimizeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 2, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.green);
        jLabel1.setText("w");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(559, 559, 559)
                .addComponent(label_Minimize)
                .addGap(18, 18, 18)
                .addComponent(label_Close)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Minimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_Close))
                .addGap(745, 745, 745))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 710));

        PanelThucdon.setBackground(new java.awt.Color(248, 148, 6));

        jPanel6.setBackground(new java.awt.Color(44, 62, 80));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH MỤC LOẠI MÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 102, 0))); // NOI18N

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        listmon.setBackground(new java.awt.Color(102, 51, 0));
        listmon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        listmon.setForeground(java.awt.Color.white);
        listmon.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        listmon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listmonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listmon);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Mã Loại Món");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Tên Loại Món");

        btn_ThemLM.setBackground(new java.awt.Color(34, 167, 240));
        btn_ThemLM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ThemLM.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThemLM.setText("Thêm");
        btn_ThemLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemLMActionPerformed(evt);
            }
        });

        btn_SuaLM.setBackground(new java.awt.Color(34, 167, 240));
        btn_SuaLM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_SuaLM.setForeground(new java.awt.Color(255, 255, 255));
        btn_SuaLM.setText("Sửa");
        btn_SuaLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaLMActionPerformed(evt);
            }
        });

        btn_XoaLM.setBackground(new java.awt.Color(242, 38, 19));
        btn_XoaLM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_XoaLM.setForeground(new java.awt.Color(255, 255, 255));
        btn_XoaLM.setText("Xóa");
        btn_XoaLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaLMActionPerformed(evt);
            }
        });

        lblguita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icon/Bài đăng Instagram Cà phê Trích dẫn Đơn giản Xanh dương.png"))); // NOI18N
        lblguita.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_TaoMoiML.setBackground(new java.awt.Color(34, 167, 240));
        btn_TaoMoiML.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_TaoMoiML.setForeground(new java.awt.Color(255, 255, 255));
        btn_TaoMoiML.setText("Tạo mới");
        btn_TaoMoiML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoMoiMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_ThemLM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_TaoMoiML)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_XoaLM, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblguita, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaLM, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(btn_SuaLM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTenLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblguita, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaLM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(btn_SuaLM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemLM)
                    .addComponent(btn_XoaLM)
                    .addComponent(btn_TaoMoiML))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(44, 62, 80));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SẢN PHẨM-MÓN ĂN-NƯỚC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(255, 0, 51));

        tbl_Mon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Món", "Tên Món", "Đơn Giá", "Mã Loại Món", "Thông Tin Hình"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Mon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_MonMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_Mon);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Danh mục::");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Mã Món:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Tên Món:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Đơn giá:");

        btn_Them.setBackground(new java.awt.Color(34, 167, 240));
        btn_Them.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_TaoMoi.setBackground(new java.awt.Color(34, 167, 240));
        btn_TaoMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_TaoMoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_TaoMoi.setText("Tạo Mới");
        btn_TaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoMoiActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(242, 38, 19));
        btn_Xoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(34, 167, 240));
        btn_Sua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        btn_ChonHinh.setBackground(new java.awt.Color(34, 167, 240));
        btn_ChonHinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ChonHinh.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChonHinh.setText("Chọn Ảnh");
        btn_ChonHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonHinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_ChonHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(btn_ChonHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_TaoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel28))
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_TenMon)
                                    .addComponent(txt_DonGia)
                                    .addComponent(txt_MaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbo_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_MaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(cbo_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txt_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_TaoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));

        lblbanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icon/Bài đăng Instagram Cà phê Trích dẫn Đơn giản Xanh dương.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblbanner, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblbanner, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelThucdonLayout = new javax.swing.GroupLayout(PanelThucdon);
        PanelThucdon.setLayout(PanelThucdonLayout);
        PanelThucdonLayout.setHorizontalGroup(
            PanelThucdonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelThucdonLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        PanelThucdonLayout.setVerticalGroup(
            PanelThucdonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelThucdonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelThucdonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelThucdonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelThucdon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(PanelThucdon, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1217, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1217, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_CloseMouseClicked

        System.exit(0);

    }//GEN-LAST:event_label_CloseMouseClicked

    private void label_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_MinimizeMouseClicked

        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_label_MinimizeMouseClicked

    private boolean CheckTrungMa(String maMon){
        List<SanPham> dssp = new ArrayList<>();
        dssp = ApiSanpham.timSanPham(maMon);
        return dssp.isEmpty();
    }
    
    private boolean IsEmpty(String maMon, String tenMon, String donGiaTxt, String maLoai){
        if (maMon.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã món không được để trống!");
                return true;
        }
        
        if (maLoai.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Loại món không được để trống!");
                return true;
        }
        
        if (tenMon.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tên món không được để trống!");
                return true;
        }
        
        if (donGiaTxt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giá không được để trống!");
            return true;
        }
        return false;
    }
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        MainJFrame sp = new MainJFrame();
        sp.setVisible(true);
        sp.pack();
        sp.setLocationRelativeTo(null);
        sp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btn_ChonHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonHinhActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn hình ảnh");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Hình ảnh", "jpg", "jpeg", "png"));

        int result = fileChooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String imagePath = selectedFile.getAbsolutePath();

            ImageIcon icon = new ImageIcon(imagePath);
            Image scaledImage = icon.getImage().getScaledInstance(lblHinh.getWidth(), lblHinh.getHeight(), Image.SCALE_SMOOTH);
            lblHinh.setIcon(new ImageIcon(scaledImage));
        }
    }//GEN-LAST:event_btn_ChonHinhActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        String maMon = txt_MaMon.getText().trim();
        String maLoai = danhMucMap.get(cbo_DanhMuc.getSelectedItem().toString().trim());
        String tenMon = txt_TenMon.getText().trim();
        String giaText = txt_DonGia.getText().trim();
        String hinhanh = lblHinh.getText().trim();

        if(IsEmpty(maMon, tenMon, giaText, maLoai)) return;

        if(CheckTrungMa(maMon)){
            JOptionPane.showMessageDialog(this, "Mã món đã tồn tại!");
            return;
        }

        long donGia = 0;
        try {
            donGia = Long.parseLong(giaText);
        } catch (NumberFormatException  e) {
            System.out.println("Giá trị không hợp lệ!");
        }

        SanPham sp = new SanPham(maMon, tenMon, donGia, maLoai, hinhanh);
        if (ApiSanpham.suaSanPham(sp)) {
            JOptionPane.showMessageDialog(null, "Sửa thành công!");
            LoadSanPham();
        }else{
            JOptionPane.showMessageDialog(null, "Sửa thất bại!");
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        String maMon = txt_MaMon.getText().trim();
        int confirm = JOptionPane.showConfirmDialog(this,
            "Bạn có chắc chắn muốn xóa sản phẩm mã: " + maMon + " không?",
            "Xác nhận xóa",
            JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        if (ApiSanpham.xoaSanPham(maMon)) {
            JOptionPane.showMessageDialog(null, "Xóa thành công!");
            LoadSanPham();
        }else{
            JOptionPane.showMessageDialog(null, "Xóa thất bại!");
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_TaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_TaoMoiActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        String maMon = txt_MaMon.getText().trim();
        String maLoai = danhMucMap.get(cbo_DanhMuc.getSelectedItem().toString().trim());
        String tenMon = txt_TenMon.getText().trim();
        String giaText = txt_DonGia.getText().trim();
        String hinhanh = lblHinh.getText().trim();
        
        if(IsEmpty(maMon, tenMon, giaText, maLoai)) return;

        if(!CheckTrungMa(maMon)){
            JOptionPane.showMessageDialog(this, "Mã món đã tồn tại!");
            return;
        }

        long donGia = 0;
        try {
            donGia = Long.parseLong(giaText);
        } catch (NumberFormatException  e) {
            System.out.println("Giá trị không hợp lệ!");
        }

        SanPham sp = new SanPham(maMon, tenMon, donGia, maLoai, hinhanh);
        if (ApiSanpham.themSanPham(sp)) {
            JOptionPane.showMessageDialog(null, "Thêm thành công!");
            LoadSanPham();
        }else{
            JOptionPane.showMessageDialog(null, "Thêm thất bại!");
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void tbl_MonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_MonMouseClicked
        // TODO add your handling code here:
        int i = tbl_Mon.getSelectedRow();
        DefaultTableModel tb = (DefaultTableModel) tbl_Mon.getModel();
        txt_MaMon.setText(tb.getValueAt(i, 0).toString());
        txt_TenMon.setText(tb.getValueAt(i, 1).toString());
        txt_DonGia.setText(tb.getValueAt(i, 2).toString());
        cbo_DanhMuc.setSelectedItem(tb.getValueAt(i, 3).toString());
       String tenFileAnh = tb.getValueAt(i, 4).toString();
        // Đường dẫn trong resource (đặt trong src/main/resources/Pictures/sanpham/)
           java.net.URL imgURL = getClass().getResource("/Pictures/sanpham/" + tenFileAnh);
           if (imgURL != null) {
               ImageIcon icon = new ImageIcon(imgURL);
               Image scaledImage = icon.getImage().getScaledInstance(
                       lblHinh.getWidth(), 
                       lblHinh.getHeight(), 
                       Image.SCALE_SMOOTH
               );
               lblHinh.setIcon(new ImageIcon(scaledImage));
           } else {
               System.err.println("Ảnh không tìm thấy trong resources/Pictures/sanpham/" + tenFileAnh);
               lblHinh.setIcon(null);
           }
        
        txt_MaMon.setEnabled(false);
    }//GEN-LAST:event_tbl_MonMouseClicked

    private void btn_XoaLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaLMActionPerformed
        // TODO add your handling code here:
        String maLoai = txtMaLM.getText().trim();
        int confirm = JOptionPane.showConfirmDialog(this,
            "Bạn có chắc chắn muốn xóa sản phẩm mã: " + maLoai + " không?",
            "Xác nhận xóa",
            JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        if (ApiLoaiMon.xoaLoaiMon(maLoai)) {
            JOptionPane.showMessageDialog(null, "Xóa thành công!");
            LoadDanhSachMon();
        }else{
            JOptionPane.showMessageDialog(null, "Xóa thất bại!");
        }
    }//GEN-LAST:event_btn_XoaLMActionPerformed

    private void btn_SuaLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaLMActionPerformed
        // TODO add your handling code here:
        String maLM = txtMaLM.getText().trim();
        String tenLm = txtTenLoaiMon.getText().trim();

        if(CheckEmpty(maLM, tenLm)) return;

        LoaiMon lm = new LoaiMon(maLM, tenLm);
        if (ApiLoaiMon.suaLoaiMon(lm)) {
            JOptionPane.showMessageDialog(null, "Sửa thành công!");
            LoadDanhSachMon();
            LoadSanPham();
        }else{
            JOptionPane.showMessageDialog(null, "Sửa thất bại!");
        }
    }//GEN-LAST:event_btn_SuaLMActionPerformed

    private boolean CheckEmpty(String maLoai, String tenLoai){
        if (maLoai.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã loại không được để trống!");
                return true;
        }
        
        if (tenLoai.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tên loại không được để trống!");
                return true;
        }
        
        return false;
    }
    
    private boolean CheckTrungMaLoai(String maLoai){
        List<LoaiMon> dssp = new ArrayList<>();
        dssp = ApiLoaiMon.timLoaiMon(maLoai);
        return dssp.isEmpty();
    }
    
    private void btn_ThemLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemLMActionPerformed
        // TODO add your handling code here:
        String maLM = txtMaLM.getText().trim();
        String tenLm = txtTenLoaiMon.getText().trim();

        if(CheckEmpty(maLM, tenLm)) return;

        if(!CheckTrungMaLoai(maLM)){
            JOptionPane.showMessageDialog(this, "Mã loại đã tồn tại!");
            return;
        }

        LoaiMon lm = new LoaiMon(maLM, tenLm);
        if (ApiLoaiMon.themLoaiMon(lm)) {
            JOptionPane.showMessageDialog(null, "Thêm thành công!");
            LoadDanhSachMon();
        }else{
            JOptionPane.showMessageDialog(null, "Thêm thất bại!");
        }
    }//GEN-LAST:event_btn_ThemLMActionPerformed

    private void listmonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listmonMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1){
            int index = listmon.locationToIndex(evt.getPoint());
            if (index != -1) {
                String selected = listmon.getModel().getElementAt(index);
                
                String[] parts = selected.split(" - ", 2);
                if (parts.length == 2) {
                    txtMaLM.setText(parts[0].trim());
                    txtTenLoaiMon.setText(parts[1].trim());
                    
                }
            }
            
            txtMaLM.setEnabled(false);
        }
    }//GEN-LAST:event_listmonMouseClicked

    private void btn_TaoMoiMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoMoiMLActionPerformed
        // TODO add your handling code here:
        txtMaLM.setText("");
        txtTenLoaiMon.setText("");
        txtMaLM.setEnabled(true);
    }//GEN-LAST:event_btn_TaoMoiMLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelThucdon;
    private javax.swing.JButton btn_ChonHinh;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_SuaLM;
    private javax.swing.JButton btn_TaoMoi;
    private javax.swing.JButton btn_TaoMoiML;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_ThemLM;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_XoaLM;
    private javax.swing.JComboBox<String> cbo_DanhMuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_Close;
    private javax.swing.JLabel label_Minimize;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblbanner;
    private javax.swing.JLabel lblguita;
    private javax.swing.JList<String> listmon;
    private javax.swing.JTable tbl_Mon;
    private javax.swing.JTextField txtMaLM;
    private javax.swing.JTextField txtTenLoaiMon;
    private javax.swing.JTextField txt_DonGia;
    private javax.swing.JTextField txt_MaMon;
    private javax.swing.JTextField txt_TenMon;
    // End of variables declaration//GEN-END:variables

}
